title: Feliz cumple, Gra!
description: > # this means to ignore newlines until "baseurl:"
  Escuchemos lo que cuentan los siguientes relatos para así formarnos una opinión más acabada de este misterioso personaje…

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Graciela # add your name
author-img: Graciela.jpg # add your photo
about-author: Aclamada madre, concubina, abuela, prima, hermana, tía, amiga, suegra, maestra...


# Build Settings
markdown: kramdown
plugins:
  - jemoji

# Emojis list: https://www.fileformat.info/info/emoji/list.htm
entries:
  - title: Gracielita
    description: 
      - <h2>Biografía no autorizada</h2>
      - Se dice que nació hace muchísimo, cuando la televisión no existía y el teléfono era un lujo.
      - Sus primos afirman que pasaba sus días de verano yendo al club (esto indicaría que provenía de “familia bienuda”). También se comenta que fumaba desde joven y bronceaba su piel al sol, provocando el enojo de su progenitor, quien no sabía qué hacer ante su actitud provocadora.
      - Tuvo una adolescencia un tanto complicada, en la que se veía forzada a ahorrar para poder pagar los sobornos que le exigía su hermana mayor.
      - Desde joven mostraba su espíritu rebelde; algunos rumores incluso indican que mostraba sus atributos usando minifaldas muy osadas para su época.
      - Su aclamado rol como maestra jardinera tendría el poder de convertir una simple caminata hasta el centro de Luján, en el más terrible e interrumpido de los periplos, tardando días en poder llegar a la plaza.
      - Sus sobrinos la recuerdan con amor, posiblemente porque los habría sobornado con golosinas y salidas al cine.
      - Habría evidencia de su rol como esposa poco sumisa, ya que fuentes confiables confirman que Graciela accedía a los licores de su esposo, al parecer para emborracharse con sus mejores amigas.
      - Sus hijos afirman que era un poco rompe bolas, pero que siempre los alentó a ser libres y felices. Por lo cual, aparentemente, estarían agradecidos.  Sin embargo, ciertas fuentes no oficiales indican que dichos hijos, habrían sometido a Graciela a penitencias tales como depositarla por largos periodos sobre diferentes muebles sin que ella, pobre santa, pudiese saltar desde los mismos.
      - Sus nueras y yernos (yernos, plural??) la admiran y le temen, ya que nunca saben con qué les va a salir. También suelen aprovecharse de su rol como segunda madre, abusando del lazo político, para demandarle atenciones del tipo culinaria (básicamente, vaciando su heladera).
      - Lectora ávida; contaría hasta el día de la fecha con una colección de libros que datan desde principio de siglo.
      - En la actualidad se destaca en su rol como abuela consagrada y revolucionaria, permitiendo que sus nietos profieran los más variados y creativos insultos libremente en su residencia de Luján de Cuyo.
      - A primera vista, daría la sensación que debajo de su apacible y dulce apariencia, se encontraría un alma revolucionaria, libre, curiosa, y creativa.
      - <b>Escuchemos lo que cuentan los siguientes relatos para así formarnos una opinión más acabada de este misterioso personaje…<b>
  - title: Guada
    description: 
      - '3 nietos! Bien ahí! Guada :heartbeat:'
    img: Guada.png
    audios:
      - Guada.mp3
  - title: Joaco
    description: 
      - '3 nietos! Bien ahí! Joaco :heartbeat:'
    img: Joaco.jpg
    audios:
      - Joaco.mp3
  - title: Montse
    description: 
      - '3 nietos! Bien ahí! Montse :heartbeat:'
    img: Monse.jpg
    audios:
      - Monse1.mp3
      - Monse2.mp3
  - title: Cele 
    description: 
      - 'Tu hijita linda, Cele :blue_heart:'
    img: Cele.png
    audios:
      - Cele.mp3
  - title: Nano
    description:
      - 'Ayyy que lindos los melli, Nano :green_heart:'
    img: Nano.jpg
    audios:
      - Nano.mp3
  - title: Eze
    description:
      - 'Ayyy que lindos los melli, Eze :yellow_heart:'
    img: Eze.jpg
    audios:
      - Eze.mp3
      - Kaval2.mp3
  - title: Pili
    description:
      - 'Hermosa nuera, no? :purple_heart:'
    img: Pili.jpg
    audios:
      - EzeyPili1.mp3
      - EzeyPili2.mp3
      - EzeyPili3.mp3
  - title: Seba
    description:
      - 'Pero que lindo muchacho :purple_heart:'
    img: Seba.png
    audios:
      - Seba.mp3
  - title: Ramiro
    description:
      - 'Otro bombón :heart_eyes:'
    img: Rama.jpg
    audios:
      - Rama.mp3
  - title: Alba 
    description:
      - 'Su querida hermanita :smiley:'
    img: Alba.jpg
    audios:
      - Alba1.mp3
      - Alba2.mp3
      - Alba3.mp3
  - title: Albi 
    description:
      - 'Su ahijada :heart_decoration:'
    img: Albi.png
    audios:
      - Albita1.mp3
      - Albita2.mp3
  - title: Juani 
    description:
      - 'El bombonazo :smile:'
    img: Juani.jpg
    audios:
      - Juani.mp3
  - title: Dorita 
    description:
      - 'Que lindo tener tantas buenas amigas :heart_eyes_cat:'
    img: Amigas.jpg
    audios:
      - Dorita1.mp3
      - Dorita2.mp3
  - title: Mabel 
    description:
      - 'Que lindo tener tantas buenas amigas :heart_eyes_cat:'
    img: Mabel.jpg
    audios:
      - Mabel.mp3
  - title: María del Carmen 
    description:
      - 'Que lindo tener tantas buenas amigas :heart_eyes_cat:'
    img: MariaDelCarmen.png
    audios:
      - MariaDelCarmen.mp3
  - title: Mercedes  
    description:
      - 'Que lindo tener tantas buenas amigas :heart_eyes_cat:'
    img: Merce.jpg
    audios:
      - Mercedes.mp3
  - title: Ulde
    description:
      - 'Que lindo tener tantas buenas amigas :heart_eyes_cat:'
    img: Ulde.jpg
    audios:
      - Ulde.mp3
  - title: Mary
    description:
      - 'Que lindo tener tantas buenas amigas :heart_eyes_cat:'
    img: MaryG.png
    audios:
      - MaryG.mp3
  - title: Erica 
    description:
      - 'Sobrina por elección :heart_eyes_cat:'
    img: Erica.png
    audios:
      - Erica1.mp3
      - Erica2.mp3
      - Erica3.mp3
  - title: Gaspar
    description:
      - 'Hablando de personas hermosas :heart_eyes_cat:'
    img: Gaspi.jpg
    audios:
      - Gaspi.mp3
  - title: Negra
    description:
      - 'Tus amad@s Prim@s :heart_eyes:'
    img: Primos.jpg
    audios:
      - Negra1.mp3
      - Negra2.mp3
      - Negra3.mp3
  - title: Mary
    description:
      - 'Tus amad@s Prim@s :heart_eyes:'
    img: Primos.jpg
    audios:
      - Mary.mp3
  - title: Mirta & flia.
    description:
      - 'Tus amad@s Prim@s :heart_eyes:'
    img: Primos.jpg
    audios:
      - Mirta1.mp3
      - Mirta2.mp3
      - Mirta3.mp3
  - title: Olga
    description:
      - 'Tus amad@s Prim@s :heart_eyes:'
    img: Primos.jpg
    audios:
      - Olga.mp3
  - title: Patin
    description:
      - 'Tus amad@s Prim@s :heart_eyes:'
    img: Primos.jpg
    audios:
      - Patin.mp3
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "Gemfile", "Gemfile.lock"]
